spring:
  thymeleaf:
    check-template-location: true
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3308/facebook
    username: root
    password: 960131
    driver-class-name: org.mariadb.jdbc.Driver
mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  type-aliases-package: com.koreait.facebook
#주석 - 톰캣 포트 변경
server:
  port: 8090
